version: '3'

services:
  oboco-backend-database:
    image: mariadb:latest
    container_name: oboco-backend-database
    environment:
      TZ: Europe/Brussels
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: oboco
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - "./application-database-data:/var/lib/mysql"
      - "./database.sql:/docker-entrypoint-initdb.d/database.sql"
    networks:
      oboco:
        aliases:
          - oboco-backend-database
  oboco-backend:
    image: registry.gitlab.com/jeeto/oboco-backend/oboco-backend-mysql:latest
    container_name: oboco-backend
    links:
      - oboco-backend-database
    environment:
      TZ: Europe/Brussels
      OBOCO_SECURITY_AUTHENTICATION_SECRET: secret
      OBOCO_DATABASE_URL: jdbc:mysql://oboco-backend-database:3306/oboco
      OBOCO_DATABASE_USER_NAME: root
      OBOCO_DATABASE_USER_PASSWORD: toor
    restart: always
    networks:
      oboco:
        aliases:
          - oboco-backend
    volumes:
      - "./application-logger-data:/application-logger-data"
      - "./application-data:/application-data"
      - "./user-data:/user-data"
  oboco-frontend:
    image: registry.gitlab.com/jeeto/oboco-frontend/oboco-frontend:latest
    container_name: oboco-frontend
    links:
      - oboco-backend
    environment:
      TZ: Europe/Brussels
      OBOCO_BASE_URL: 
    restart: always
    networks:
      oboco:
        aliases:
          - oboco-frontend
  oboco-backend-frontend:
    depends_on:
      - oboco-frontend
      - oboco-backend
    image: nginx:alpine
    container_name: oboco-backend-frontend
    volumes: 
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      oboco:
        aliases:
          - oboco-backend-frontend
    ports:
        - "80:80"
networks:
    oboco: